apiVersion: v1
kind: Secret
metadata:
  name: {{ include "umap.fullname" . }}-env
  labels:
    {{- include "umap.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.umap.environment }}
  {{ $key }}: "{{ $value | b64enc }}"
{{- end }}